openapi: '3.0.2'
info:
  title: Mio 3rd Anniversary Fan-Website API
  version: '1.0.0'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: 'https://api.miosha.moe/anniv3/{version}'
    description: Live server
    variables:
      version:
        enum:
          - dev
        default: dev
        description: The API version.
  - url: 'http://localhost:{port}'
    description: Locally-hosted server
    variables:
      port:
        default: '8855'
        description: The port the server listens to

paths:
  /messages:
    get:
      tags:
        - Public
        - Messages
      summary: Retrieves posted messages.
      description: >
        Retrieves posted messages in a paginated format.

        There is no guarantee that the message list will not change between calls
        to this method, so the same call in different points in time may give different results.
      operationId: getMessages
      x-eov-operation-handler: messagesHandler
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          required: true
          description: The number of the page to retrieve
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            maximum: 100
          required: true
          description: The number of items to use per page
      responses:
        '200':
          description: Page found and returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    description: The number of the page that was retrieved
                  pageSize:
                    type: integer
                    description: The maximum size of the page
                  pageCount:
                    type: integer
                    description: The number of pages that exist with the given page size
                  pageData:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: There is no page with the given number for the given page size
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Error'
                  - type: object
                    properties:
                      pageCount:
                        type: integer
                        description: The number of pages that exist with the given page size
                    required:
                      - pageCount
    post:
      tags:
        - Public
        - Messages
        - Submission
      summary: Posts a new message.
      operationId: postMessage
      x-eov-operation-handler: messagesHandler
      requestBody:
        description: The content of the message to post
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageContent'
      responses:
        '201':
          description: Message posted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageMetadata'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          description: >
            There is already a message with the given author name or email.
            The response body provides the ID and posting time of the existing message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          $ref: '#/components/responses/RateLimit'

  /messages/admin:
    get:
      tags:
        - Admin
        - Messages
      summary: Retrieves posted messages, either approved or pending.
      description: >
        Retrieves posted messages in a paginated format.

        There is no guarantee that the message list will not change between calls
        to this method, so the same call in different points in time may give different results.
      operationId: getMessagesAdmin
      x-eov-operation-handler: messagesHandler
      security:
        - ApiKeyAuth: [ 'admin' ]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          required: true
          description: The number of the page to retrieve
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            maximum: 100
          required: true
          description: The number of items to use per page
        - in: query
          name: pending
          schema:
            type: boolean
          required: true
          description: |
            If true, retrives only the pending messages, otherwise retrives only approved messages.
            In the latter case, this method is equivalent to `GET /messages`.
      responses:
        '200':
          description: Page found and returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    description: The number of the page that was retrieved
                  pageSize:
                    type: integer
                    description: The maximum size of the page
                  pageCount:
                    type: integer
                    description: The number of pages that exist with the given page size
                  pageData:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: There is no page with the given number for the given page size
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Error'
                  - type: object
                    properties:
                      pageCount:
                        type: integer
                        description: The number of pages that exist with the given page size
                    required:
                      - pageCount
    put:
      tags:
        - Admin
        - Messages
      summary: Sets a message to approved or pending.
      operationId: putMessagesAdmin
      x-eov-operation-handler: messagesHandler
      security:
        - ApiKeyAuth: [ 'admin' ]
      parameters:
        - in: query
          name: id
          schema:
            $ref: '#/components/schemas/MessageId'
          required: true
          description: The ID of the message to set
        - in: query
          name: approve
          schema:
            type: boolean
          required: true
          description: |
            If true, sets the message as approved.
            Otherwise, sets it to pending.
      responses:
        '204':
          description: The change was performed successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/MessageNotFound'
    delete:
      tags:
        - Admin
        - Messages
      summary: Removes a message from the system.
      operationId: deleteMessagesAdmin
      x-eov-operation-handler: messagesHandler
      security:
        - ApiKeyAuth: [ 'admin' ]
      parameters:
        - in: query
          name: id
          schema:
            $ref: '#/components/schemas/MessageId'
          required: true
          description: The ID of the message to delete
        - in: query
          name: ban
          schema:
            type: boolean
          required: true
          description: If true, the message poster is prevented from posting again
      responses:
        '204':
          description: The message was deleted successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/MessageNotFound'
      

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  responses:
    BadRequest:
      description: The request sent by the client was malformed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Missing or invalid user authentication
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: User does not have sufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    RateLimit:
      description: The user has sent too many requests in a short amount of time
      headers:
        Retry-After:
          schema:
            type: integer
          description: How many seconds to wait before trying again
    MessageNotFound:
      description: There is no message with the given ID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
      required:
        - status
        - message
    MessageAuthor:
      description: A user that posts a message
      type: object
      properties:
        name:
          description: The name of the user
          type: string
          minLength: 1
          maxLength: 20
        email:
          description: |
            The user's email. This value must be present when posting a message, but it will
            not be returned by any method in this API. The email must be a valid.
          type: string
          format: email
        avatar:
          description: | 
            The image frames that compose the animated user avatar.
            If a single frame, the avatar is a static image.
            May be empty, in which case a default avatar is used.
          type: array
          maxItems: 2
          items:
            type: string
            format: uri
            maxLength: 500
      required:
        - name
        - avatar
    MessageId:
      description: The ID of a message
      type: integer
    MessageContent:
      description: The main data of a message
      type: object
      properties:
        author:
          $ref: '#/components/schemas/MessageAuthor'
        content:
          description: The content of the message
          type: string
          minLength: 1
          maxLength: 500
      required:
        - author
        - content
    MessageMetadata:
      description: The metadata of a message
      type: object
      properties:
        id:
          $ref: '#/components/schemas/MessageId'
        timestamp:
          description: The timestamp of when the message was posted
          type: string
          format: date-time
      required:
        - id
        - timestamp
    Message:
      allOf:
        - $ref: '#/components/schemas/MessageMetadata'
        - $ref: '#/components/schemas/MessageContent'